package com.lyf.bookreader.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lyf.bookreader.javabean.BookCase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_CASE".
*/
public class BookCaseDao extends AbstractDao<BookCase, Void> {

    public static final String TABLENAME = "BOOK_CASE";

    /**
     * Properties of entity BookCase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Bookname = new Property(0, String.class, "bookname", false, "BOOKNAME");
        public final static Property Author = new Property(1, String.class, "author", false, "AUTHOR");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Finish = new Property(3, String.class, "finish", false, "FINISH");
        public final static Property Img = new Property(4, String.class, "img", false, "IMG");
        public final static Property CurPage = new Property(5, int.class, "curPage", false, "CUR_PAGE");
        public final static Property Position = new Property(6, int.class, "position", false, "POSITION");
        public final static Property Total = new Property(7, int.class, "total", false, "TOTAL");
        public final static Property Type = new Property(8, String.class, "type", false, "TYPE");
    };


    public BookCaseDao(DaoConfig config) {
        super(config);
    }
    
    public BookCaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_CASE\" (" + //
                "\"BOOKNAME\" TEXT," + // 0: bookname
                "\"AUTHOR\" TEXT," + // 1: author
                "\"TIME\" TEXT," + // 2: time
                "\"FINISH\" TEXT," + // 3: finish
                "\"IMG\" TEXT," + // 4: img
                "\"CUR_PAGE\" INTEGER NOT NULL ," + // 5: curPage
                "\"POSITION\" INTEGER NOT NULL ," + // 6: position
                "\"TOTAL\" INTEGER NOT NULL ," + // 7: total
                "\"TYPE\" TEXT);"); // 8: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_CASE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookCase entity) {
        stmt.clearBindings();
 
        String bookname = entity.getBookname();
        if (bookname != null) {
            stmt.bindString(1, bookname);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(2, author);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String finish = entity.getFinish();
        if (finish != null) {
            stmt.bindString(4, finish);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(5, img);
        }
        stmt.bindLong(6, entity.getCurPage());
        stmt.bindLong(7, entity.getPosition());
        stmt.bindLong(8, entity.getTotal());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookCase entity) {
        stmt.clearBindings();
 
        String bookname = entity.getBookname();
        if (bookname != null) {
            stmt.bindString(1, bookname);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(2, author);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String finish = entity.getFinish();
        if (finish != null) {
            stmt.bindString(4, finish);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(5, img);
        }
        stmt.bindLong(6, entity.getCurPage());
        stmt.bindLong(7, entity.getPosition());
        stmt.bindLong(8, entity.getTotal());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(9, type);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BookCase readEntity(Cursor cursor, int offset) {
        BookCase entity = new BookCase( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // bookname
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // author
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // finish
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // img
            cursor.getInt(offset + 5), // curPage
            cursor.getInt(offset + 6), // position
            cursor.getInt(offset + 7), // total
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookCase entity, int offset) {
        entity.setBookname(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAuthor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFinish(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImg(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCurPage(cursor.getInt(offset + 5));
        entity.setPosition(cursor.getInt(offset + 6));
        entity.setTotal(cursor.getInt(offset + 7));
        entity.setType(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BookCase entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BookCase entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
