package com.lyf.bookreader.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lyf.bookreader.javabean.Book;
import com.lyf.bookreader.javabean.BookCase;
import com.lyf.bookreader.javabean.Chapter;
import com.lyf.bookreader.javabean.RecentlyRead;
import com.lyf.bookreader.javabean.SearchEntity;

import com.lyf.bookreader.db.BookDao;
import com.lyf.bookreader.db.BookCaseDao;
import com.lyf.bookreader.db.ChapterDao;
import com.lyf.bookreader.db.RecentlyReadDao;
import com.lyf.bookreader.db.SearchEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig bookCaseDaoConfig;
    private final DaoConfig chapterDaoConfig;
    private final DaoConfig recentlyReadDaoConfig;
    private final DaoConfig searchEntityDaoConfig;

    private final BookDao bookDao;
    private final BookCaseDao bookCaseDao;
    private final ChapterDao chapterDao;
    private final RecentlyReadDao recentlyReadDao;
    private final SearchEntityDao searchEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        bookCaseDaoConfig = daoConfigMap.get(BookCaseDao.class).clone();
        bookCaseDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        recentlyReadDaoConfig = daoConfigMap.get(RecentlyReadDao.class).clone();
        recentlyReadDaoConfig.initIdentityScope(type);

        searchEntityDaoConfig = daoConfigMap.get(SearchEntityDao.class).clone();
        searchEntityDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        bookCaseDao = new BookCaseDao(bookCaseDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);
        recentlyReadDao = new RecentlyReadDao(recentlyReadDaoConfig, this);
        searchEntityDao = new SearchEntityDao(searchEntityDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(BookCase.class, bookCaseDao);
        registerDao(Chapter.class, chapterDao);
        registerDao(RecentlyRead.class, recentlyReadDao);
        registerDao(SearchEntity.class, searchEntityDao);
    }
    
    public void clear() {
        bookDaoConfig.getIdentityScope().clear();
        bookCaseDaoConfig.getIdentityScope().clear();
        chapterDaoConfig.getIdentityScope().clear();
        recentlyReadDaoConfig.getIdentityScope().clear();
        searchEntityDaoConfig.getIdentityScope().clear();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public BookCaseDao getBookCaseDao() {
        return bookCaseDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public RecentlyReadDao getRecentlyReadDao() {
        return recentlyReadDao;
    }

    public SearchEntityDao getSearchEntityDao() {
        return searchEntityDao;
    }

}
